#!/usr/bin/env bash
set -xeuo pipefail

GAME="${1:-demo}"
NAMESPACE="examples.${GAME}.core"

jank \
  -Ilibs/glfw/include -Ilibs/glm -Iinclude -Ilibs/ozz-animation/include \
  -Llibs/glfw/lib -llibglfw.3.dylib \
  -Llibs/ozz-animation/lib -llibozz_animation.dylib -llibozz_base.dylib -llibozz_geometry.dylib \
  --module-path $(clojure -Spath) run-main "$NAMESPACE"
