;; Walks one or more asset directories and emits a single .cpp file containing
;; every file as a static byte array, plus an extern "C" engine_register_resources
;; function that calls jank_resource_register for each.
;;
;; Also emits two functions describing engine-built-in include paths (so the
;; runtime binary knows which paths to add to the JIT's clang search path
;; without the consumer having to specify them):
;;   engine_built_includes_count()
;;   engine_built_includes_at(i) -> char const *
;;
;; Usage:
;;   clojure -M scripts/embed-assets.clj <output.cpp> \
;;       [--system-include PATH ...] \
;;       <asset-root> [<asset-root> ...]
;;
;; Each <asset-root> is paired as: PREFIX:DIR
;; Example:  shaders:./shaders fonts:./fonts
;; produces registry keys like "shaders/basic_vertex.glsl", "fonts/JetBrainsMono-Regular.ttf".

(ns embed-assets
  (:require [clojure.java.io :as io]
            [clojure.string :as str])
  (:import [java.io File OutputStreamWriter]
           [java.nio.file Files]))

(defn ^String relative-path
  [^File root ^File f]
  (-> (.toURI root) (.relativize (.toURI f)) (.getPath)))

(defn ^bytes file-bytes
  [^File f]
  (Files/readAllBytes (.toPath f)))

(defn c-identifier
  [logical]
  (-> logical (str/replace #"[^A-Za-z0-9]" "_")))

(defn write-byte-array
  [^OutputStreamWriter out ident ^bytes data]
  (.write out (str "static unsigned char const " ident "[] = {"))
  (let [n (alength data)]
    (dotimes [i n]
      (when (zero? (mod i 16))
        (.write out "\n  "))
      (.write out (format "0x%02X" (bit-and (aget data i) 0xFF)))
      (when (< i (dec n)) (.write out ","))))
  (.write out "\n};\n")
  (.write out (str "static unsigned long const " ident "_size = " (alength data) ";\n\n")))

(defn collect-files
  [^File root]
  (->> (file-seq root)
       (filter #(.isFile ^File %))
       (sort-by #(.getPath ^File %))))

(defn parse-root-spec
  "Parse 'prefix:path' into [prefix path]. Either side can be missing."
  [spec]
  (let [idx (.indexOf ^String spec ":")]
    (if (neg? idx)
      ["" spec]
      [(subs spec 0 idx) (subs spec (inc idx))])))

(defn parse-cli
  "Returns {:output s :system-includes [s ...] :asset-specs [s ...]}."
  [argv]
  (when (empty? argv)
    (binding [*out* *err*]
      (println "usage: embed-assets.clj <output.cpp> [--system-include PATH ...] <prefix:dir> [<prefix:dir> ...]"))
    (System/exit 2))
  (loop [includes []
         specs    []
         remaining (rest argv)]
    (cond
      (empty? remaining)
      {:output (first argv) :system-includes includes :asset-specs specs}

      (= "--system-include" (first remaining))
      (let [p (second remaining)]
        (when (nil? p)
          (binding [*out* *err*]
            (println "--system-include requires a path"))
          (System/exit 2))
        (recur (conj includes p) specs (drop 2 remaining)))

      :else
      (recur includes (conj specs (first remaining)) (rest remaining)))))

(defn -main
  [& argv]
  (let [{:keys [output system-includes asset-specs]} (parse-cli argv)]
    (when (and (empty? asset-specs) (empty? system-includes))
      (binding [*out* *err*]
        (println "nothing to embed (no asset specs, no --system-include)"))
      (System/exit 2))
    (io/make-parents output)
    (let [entries (atom [])]
      (with-open [out (io/writer output)]
        (.write out "// Generated by scripts/embed-assets.clj. Do not edit.\n")
        (.write out "#include <jank/c_api.h>\n")
        (.write out "#include <cstddef>\n\n")
        (doseq [spec asset-specs]
          (let [[prefix dir] (parse-root-spec spec)
                root         (io/file dir)]
            (when-not (.isDirectory root)
              (binding [*out* *err*]
                (println (str "asset root not a directory: " dir)))
              (System/exit 1))
            (doseq [^File f (collect-files root)]
              (let [rel    (relative-path root f)
                    logical (if (empty? prefix) rel (str prefix "/" rel))
                    ident   (str "asset_" (c-identifier logical))
                    data    (file-bytes f)]
                (write-byte-array out ident data)
                (swap! entries conj [logical ident])))))
        (.write out "extern \"C\" void engine_register_resources()\n{\n")
        (.write out "  static bool initialized = false;\n")
        (.write out "  if(initialized) { return; }\n")
        (.write out "  initialized = true;\n")
        (doseq [[logical ident] @entries]
          (.write out (format "  jank_resource_register(\"%s\", (char const *)%s, (jank_usize)%s_size);\n"
                              logical ident ident)))
        (.write out "}\n\n")
        ;; Emit the built-in include path table.
        (.write out (format "extern \"C\" std::size_t engine_built_includes_count() { return %d; }\n"
                            (count system-includes)))
        (.write out "extern \"C\" char const *engine_built_includes_at(std::size_t i)\n{\n")
        (if (empty? system-includes)
          (.write out "  (void)i; return nullptr;\n")
          (do (.write out "  static char const *paths[] = {\n")
              (doseq [p system-includes]
                (.write out (format "    \"%s\",\n" p)))
              (.write out "  };\n")
              (.write out (format "  if(i >= %d) { return nullptr; }\n" (count system-includes)))
              (.write out "  return paths[i];\n")))
        (.write out "}\n"))
      (binding [*out* *err*]
        (println (str "embedded " (count @entries) " assets and "
                      (count system-includes) " include paths into " output))))))

(apply -main *command-line-args*)
