;; Walks one or more asset directories and emits a C++ header containing
;; every file as a static byte array, plus an inline engine_register_resources
;; function that calls jank_resource_register for each.
;;
;; Usage: bb scripts/embed-assets.clj <output.h> <prefix:directory> ...

(ns embed-assets
  (:require [clojure.java.io :as io]
            [clojure.string :as str])
  (:import [java.io File OutputStreamWriter]
           [java.nio.file Files]))

(defn ^String relative-path
  [^File root ^File f]
  (-> (.toURI root) (.relativize (.toURI f)) (.getPath)))

(defn ^bytes file-bytes
  [^File f]
  (Files/readAllBytes (.toPath f)))

(defn c-identifier
  [logical]
  (-> logical (str/replace #"[^A-Za-z0-9]" "_")))

(defn write-byte-array
  [^OutputStreamWriter out ident ^bytes data]
  (.write out (str "static unsigned char const " ident "[] = {"))
  (let [n (alength data)]
    (dotimes [i n]
      (when (zero? (mod i 16))
        (.write out "\n  "))
      (.write out (format "0x%02X" (bit-and (aget data i) 0xFF)))
      (when (< i (dec n)) (.write out ","))))
  (.write out "\n};\n")
  (.write out (str "static unsigned long const " ident "_size = " (alength data) ";\n\n")))

(defn collect-files
  [^File root]
  (->> (file-seq root)
       (filter #(.isFile ^File %))
       (sort-by #(.getPath ^File %))))

(defn parse-root-spec
  "Parse 'prefix:path' into [prefix path]. Either side can be missing."
  [spec]
  (let [idx (.indexOf ^String spec ":")]
    (if (neg? idx)
      ["" spec]
      [(subs spec 0 idx) (subs spec (inc idx))])))

(defn -main
  [& argv]
  (let [[output & asset-specs] argv]
    (when (or (nil? output) (empty? asset-specs))
      (binding [*out* *err*]
        (println "usage: embed-assets.clj <output.h> <prefix:directory> ..."))
      (System/exit 2))
    (io/make-parents output)
    (let [entries (atom [])]
      (with-open [out (io/writer output)]
        (.write out "// Generated by scripts/embed-assets.clj. Do not edit.\n#pragma once\n")
        (.write out "#include <jank/c_api.h>\n")
        (.write out "#include <cstddef>\n\n")
        (doseq [spec asset-specs]
          (let [[prefix dir] (parse-root-spec spec)
                root         (io/file dir)]
            (when-not (.isDirectory root)
              (binding [*out* *err*]
                (println (str "asset root not a directory: " dir)))
              (System/exit 1))
            (doseq [^File f (collect-files root)]
              (let [rel    (relative-path root f)
                    logical (if (empty? prefix) rel (str prefix "/" rel))
                    ident   (str "asset_" (c-identifier logical))
                    data    (file-bytes f)]
                (write-byte-array out ident data)
                (swap! entries conj [logical ident])))))
        (.write out "inline void engine_register_resources()\n{\n")
        (.write out "  static bool initialized = false;\n")
        (.write out "  if(initialized) { return; }\n")
        (.write out "  initialized = true;\n")
        (doseq [[logical ident] @entries]
          (.write out (format "  jank_resource_register(\"%s\", (char const *)%s, (jank_usize)%s_size);\n"
                              logical ident ident)))
        (.write out "}\n\n"))
      (binding [*out* *err*]
        (println (str "embedded " (count @entries) " assets into " output))))))

(apply -main *command-line-args*)
