cmake_minimum_required(VERSION 3.24)
project(engine_native LANGUAGES C CXX)

set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_INSTALL_NAME_DIR "@rpath")
set(CMAKE_BUILD_WITH_INSTALL_NAME_DIR ON)
if(APPLE)
  set(CMAKE_INSTALL_RPATH "@loader_path")
endif()
set(ozz_build_samples OFF CACHE BOOL "" FORCE)
set(ozz_build_howtos OFF CACHE BOOL "" FORCE)
set(ozz_build_tools OFF CACHE BOOL "" FORCE)
set(ozz_build_tests OFF CACHE BOOL "" FORCE)
set(ozz_build_postfix OFF CACHE BOOL "" FORCE)
add_subdirectory(../third_party/ozz-animation ozz)

foreach(lib stb_all cgltf enet)
  add_library(${lib} ${lib}.c)
  target_include_directories(${lib} PRIVATE ../include)
  install(TARGETS ${lib} DESTINATION lib)
endforeach()
if(UNIX AND NOT APPLE)
  target_link_libraries(stb_all PRIVATE m)
endif()

install(DIRECTORY ../include/ ../libs/glm/glm DESTINATION include)
